// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	"github.com/bborbe/git-rest/pkg/metrics"
)

type FakeMetrics struct {
	IncConflictPathsStub        func(int)
	incConflictPathsMutex       sync.RWMutex
	incConflictPathsArgsForCall []struct {
		arg1 int
	}
	IncGitOperationErrorStub        func(string)
	incGitOperationErrorMutex       sync.RWMutex
	incGitOperationErrorArgsForCall []struct {
		arg1 string
	}
	IncHTTPRequestStub        func(string, string, string)
	incHTTPRequestMutex       sync.RWMutex
	incHTTPRequestArgsForCall []struct {
		arg1 string
		arg2 string
		arg3 string
	}
	IncMergeOutcomeStub        func(string)
	incMergeOutcomeMutex       sync.RWMutex
	incMergeOutcomeArgsForCall []struct {
		arg1 string
	}
	IncRebaseConflictStub        func()
	incRebaseConflictMutex       sync.RWMutex
	incRebaseConflictArgsForCall []struct {
	}
	ObserveGitOperationStub        func(string, float64)
	observeGitOperationMutex       sync.RWMutex
	observeGitOperationArgsForCall []struct {
		arg1 string
		arg2 float64
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeMetrics) IncConflictPaths(arg1 int) {
	fake.incConflictPathsMutex.Lock()
	fake.incConflictPathsArgsForCall = append(fake.incConflictPathsArgsForCall, struct {
		arg1 int
	}{arg1})
	stub := fake.IncConflictPathsStub
	fake.recordInvocation("IncConflictPaths", []interface{}{arg1})
	fake.incConflictPathsMutex.Unlock()
	if stub != nil {
		fake.IncConflictPathsStub(arg1)
	}
}

func (fake *FakeMetrics) IncConflictPathsCallCount() int {
	fake.incConflictPathsMutex.RLock()
	defer fake.incConflictPathsMutex.RUnlock()
	return len(fake.incConflictPathsArgsForCall)
}

func (fake *FakeMetrics) IncConflictPathsCalls(stub func(int)) {
	fake.incConflictPathsMutex.Lock()
	defer fake.incConflictPathsMutex.Unlock()
	fake.IncConflictPathsStub = stub
}

func (fake *FakeMetrics) IncConflictPathsArgsForCall(i int) int {
	fake.incConflictPathsMutex.RLock()
	defer fake.incConflictPathsMutex.RUnlock()
	argsForCall := fake.incConflictPathsArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeMetrics) IncGitOperationError(arg1 string) {
	fake.incGitOperationErrorMutex.Lock()
	fake.incGitOperationErrorArgsForCall = append(fake.incGitOperationErrorArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.IncGitOperationErrorStub
	fake.recordInvocation("IncGitOperationError", []interface{}{arg1})
	fake.incGitOperationErrorMutex.Unlock()
	if stub != nil {
		fake.IncGitOperationErrorStub(arg1)
	}
}

func (fake *FakeMetrics) IncGitOperationErrorCallCount() int {
	fake.incGitOperationErrorMutex.RLock()
	defer fake.incGitOperationErrorMutex.RUnlock()
	return len(fake.incGitOperationErrorArgsForCall)
}

func (fake *FakeMetrics) IncGitOperationErrorCalls(stub func(string)) {
	fake.incGitOperationErrorMutex.Lock()
	defer fake.incGitOperationErrorMutex.Unlock()
	fake.IncGitOperationErrorStub = stub
}

func (fake *FakeMetrics) IncGitOperationErrorArgsForCall(i int) string {
	fake.incGitOperationErrorMutex.RLock()
	defer fake.incGitOperationErrorMutex.RUnlock()
	argsForCall := fake.incGitOperationErrorArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeMetrics) IncHTTPRequest(arg1 string, arg2 string, arg3 string) {
	fake.incHTTPRequestMutex.Lock()
	fake.incHTTPRequestArgsForCall = append(fake.incHTTPRequestArgsForCall, struct {
		arg1 string
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.IncHTTPRequestStub
	fake.recordInvocation("IncHTTPRequest", []interface{}{arg1, arg2, arg3})
	fake.incHTTPRequestMutex.Unlock()
	if stub != nil {
		fake.IncHTTPRequestStub(arg1, arg2, arg3)
	}
}

func (fake *FakeMetrics) IncHTTPRequestCallCount() int {
	fake.incHTTPRequestMutex.RLock()
	defer fake.incHTTPRequestMutex.RUnlock()
	return len(fake.incHTTPRequestArgsForCall)
}

func (fake *FakeMetrics) IncHTTPRequestCalls(stub func(string, string, string)) {
	fake.incHTTPRequestMutex.Lock()
	defer fake.incHTTPRequestMutex.Unlock()
	fake.IncHTTPRequestStub = stub
}

func (fake *FakeMetrics) IncHTTPRequestArgsForCall(i int) (string, string, string) {
	fake.incHTTPRequestMutex.RLock()
	defer fake.incHTTPRequestMutex.RUnlock()
	argsForCall := fake.incHTTPRequestArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeMetrics) IncMergeOutcome(arg1 string) {
	fake.incMergeOutcomeMutex.Lock()
	fake.incMergeOutcomeArgsForCall = append(fake.incMergeOutcomeArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.IncMergeOutcomeStub
	fake.recordInvocation("IncMergeOutcome", []interface{}{arg1})
	fake.incMergeOutcomeMutex.Unlock()
	if stub != nil {
		fake.IncMergeOutcomeStub(arg1)
	}
}

func (fake *FakeMetrics) IncMergeOutcomeCallCount() int {
	fake.incMergeOutcomeMutex.RLock()
	defer fake.incMergeOutcomeMutex.RUnlock()
	return len(fake.incMergeOutcomeArgsForCall)
}

func (fake *FakeMetrics) IncMergeOutcomeCalls(stub func(string)) {
	fake.incMergeOutcomeMutex.Lock()
	defer fake.incMergeOutcomeMutex.Unlock()
	fake.IncMergeOutcomeStub = stub
}

func (fake *FakeMetrics) IncMergeOutcomeArgsForCall(i int) string {
	fake.incMergeOutcomeMutex.RLock()
	defer fake.incMergeOutcomeMutex.RUnlock()
	argsForCall := fake.incMergeOutcomeArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeMetrics) IncRebaseConflict() {
	fake.incRebaseConflictMutex.Lock()
	fake.incRebaseConflictArgsForCall = append(fake.incRebaseConflictArgsForCall, struct {
	}{})
	stub := fake.IncRebaseConflictStub
	fake.recordInvocation("IncRebaseConflict", []interface{}{})
	fake.incRebaseConflictMutex.Unlock()
	if stub != nil {
		fake.IncRebaseConflictStub()
	}
}

func (fake *FakeMetrics) IncRebaseConflictCallCount() int {
	fake.incRebaseConflictMutex.RLock()
	defer fake.incRebaseConflictMutex.RUnlock()
	return len(fake.incRebaseConflictArgsForCall)
}

func (fake *FakeMetrics) IncRebaseConflictCalls(stub func()) {
	fake.incRebaseConflictMutex.Lock()
	defer fake.incRebaseConflictMutex.Unlock()
	fake.IncRebaseConflictStub = stub
}

func (fake *FakeMetrics) ObserveGitOperation(arg1 string, arg2 float64) {
	fake.observeGitOperationMutex.Lock()
	fake.observeGitOperationArgsForCall = append(fake.observeGitOperationArgsForCall, struct {
		arg1 string
		arg2 float64
	}{arg1, arg2})
	stub := fake.ObserveGitOperationStub
	fake.recordInvocation("ObserveGitOperation", []interface{}{arg1, arg2})
	fake.observeGitOperationMutex.Unlock()
	if stub != nil {
		fake.ObserveGitOperationStub(arg1, arg2)
	}
}

func (fake *FakeMetrics) ObserveGitOperationCallCount() int {
	fake.observeGitOperationMutex.RLock()
	defer fake.observeGitOperationMutex.RUnlock()
	return len(fake.observeGitOperationArgsForCall)
}

func (fake *FakeMetrics) ObserveGitOperationCalls(stub func(string, float64)) {
	fake.observeGitOperationMutex.Lock()
	defer fake.observeGitOperationMutex.Unlock()
	fake.ObserveGitOperationStub = stub
}

func (fake *FakeMetrics) ObserveGitOperationArgsForCall(i int) (string, float64) {
	fake.observeGitOperationMutex.RLock()
	defer fake.observeGitOperationMutex.RUnlock()
	argsForCall := fake.observeGitOperationArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeMetrics) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeMetrics) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ metrics.Metrics = new(FakeMetrics)
