// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	"github.com/bborbe/git-rest/pkg/puller"
)

type FakePullStateWriter struct {
	RecordPullStub        func(error)
	recordPullMutex       sync.RWMutex
	recordPullArgsForCall []struct {
		arg1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakePullStateWriter) RecordPull(arg1 error) {
	fake.recordPullMutex.Lock()
	fake.recordPullArgsForCall = append(fake.recordPullArgsForCall, struct {
		arg1 error
	}{arg1})
	stub := fake.RecordPullStub
	fake.recordInvocation("RecordPull", []interface{}{arg1})
	fake.recordPullMutex.Unlock()
	if stub != nil {
		fake.RecordPullStub(arg1)
	}
}

func (fake *FakePullStateWriter) RecordPullCallCount() int {
	fake.recordPullMutex.RLock()
	defer fake.recordPullMutex.RUnlock()
	return len(fake.recordPullArgsForCall)
}

func (fake *FakePullStateWriter) RecordPullCalls(stub func(error)) {
	fake.recordPullMutex.Lock()
	defer fake.recordPullMutex.Unlock()
	fake.RecordPullStub = stub
}

func (fake *FakePullStateWriter) RecordPullArgsForCall(i int) error {
	fake.recordPullMutex.RLock()
	defer fake.recordPullMutex.RUnlock()
	argsForCall := fake.recordPullArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakePullStateWriter) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakePullStateWriter) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ puller.PullStateWriter = new(FakePullStateWriter)
