// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	"github.com/bborbe/git-rest/pkg/handler"
)

type FakeReadinessStateReader struct {
	ReadinessStatusStub        func() (bool, string)
	readinessStatusMutex       sync.RWMutex
	readinessStatusArgsForCall []struct {
	}
	readinessStatusReturns struct {
		result1 bool
		result2 string
	}
	readinessStatusReturnsOnCall map[int]struct {
		result1 bool
		result2 string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeReadinessStateReader) ReadinessStatus() (bool, string) {
	fake.readinessStatusMutex.Lock()
	ret, specificReturn := fake.readinessStatusReturnsOnCall[len(fake.readinessStatusArgsForCall)]
	fake.readinessStatusArgsForCall = append(fake.readinessStatusArgsForCall, struct {
	}{})
	stub := fake.ReadinessStatusStub
	fakeReturns := fake.readinessStatusReturns
	fake.recordInvocation("ReadinessStatus", []interface{}{})
	fake.readinessStatusMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeReadinessStateReader) ReadinessStatusCallCount() int {
	fake.readinessStatusMutex.RLock()
	defer fake.readinessStatusMutex.RUnlock()
	return len(fake.readinessStatusArgsForCall)
}

func (fake *FakeReadinessStateReader) ReadinessStatusCalls(stub func() (bool, string)) {
	fake.readinessStatusMutex.Lock()
	defer fake.readinessStatusMutex.Unlock()
	fake.ReadinessStatusStub = stub
}

func (fake *FakeReadinessStateReader) ReadinessStatusReturns(result1 bool, result2 string) {
	fake.readinessStatusMutex.Lock()
	defer fake.readinessStatusMutex.Unlock()
	fake.ReadinessStatusStub = nil
	fake.readinessStatusReturns = struct {
		result1 bool
		result2 string
	}{result1, result2}
}

func (fake *FakeReadinessStateReader) ReadinessStatusReturnsOnCall(i int, result1 bool, result2 string) {
	fake.readinessStatusMutex.Lock()
	defer fake.readinessStatusMutex.Unlock()
	fake.ReadinessStatusStub = nil
	if fake.readinessStatusReturnsOnCall == nil {
		fake.readinessStatusReturnsOnCall = make(map[int]struct {
			result1 bool
			result2 string
		})
	}
	fake.readinessStatusReturnsOnCall[i] = struct {
		result1 bool
		result2 string
	}{result1, result2}
}

func (fake *FakeReadinessStateReader) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeReadinessStateReader) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ handler.ReadinessStateReader = new(FakeReadinessStateReader)
